# This file controls the build options of the projects rtCore, rtRemote, pxscene and pxwayland from the component pxcore-libnode
# The file is also used in projects rtrmfplayer and rdkbrowser2 from other components

# Uncomment this line to use shared versions of libraries
#export USE_PXCORE_SHARED_LIBS = "TRUE"

# Uncomment this line to do not use westeros-compositor library
#export DISABLE_WESTEROS = "TRUE"

# Uncomment this line to define DISABLE_WAYLAND macro during the compilation
#export DISABLE_WAYLAND = "TRUE"
